### ISSUE TITLE
toBeOneOf in extra 3-magic-8-ball test not working

### ISSUE THREAD

**Issue by pigos4** [CodeYourFuture/JavaScript-Core-1-Coursework-Week1#224]
<img width="1792" alt="Screenshot 2021-12-12 at 15 53 02" src="https://user-images.githubusercontent.com/64493498/145719885-2767cac6-ee24-4fa8-a1bf-38719b614266.png">
<img width="1792" alt="Screenshot 2021-12-12 at 15 52 53" src="https://user-images.githubusercontent.com/64493498/145719889-67bb6dd6-da27-4493-b275-ab0c1ce4fbe6.png">
I've found a problem with the test toBeOneOf I've added see the screenshot

**Comment by ChrisOwen101** [comment]
What seems to be the problem @pigos4 ? It seems like all the tests are passing here

**Comment by pigos4** [comment]
<img width="766" alt="Screenshot 2021-12-12 at 18 52 35" src="https://user-images.githubusercontent.com/64493498/145725561-bb7abdf5-d4bd-44a2-9ed5-23c3a9efc425.png">
Yes sorry this is the correct screenshot @ChrisOwen101

**Comment by michellejanaycodes** [comment]
Hi, I second this issue. The Magic 8 Ball test will fail unless the checkAnswer.toBeOneOf is commented out. It is also failing in the pull request.  

`test("whole magic 8 ball sequence", () => {
  const consoleLogSpy = jest.spyOn(global.console, "log");
  const answer = shakeBall();

  expect(typeof answer).toEqual("string");

  expect(consoleLogSpy).toHaveBeenCalledTimes(1);
  expect(consoleLogSpy).toHaveBeenLastCalledWith("The ball has shaken!");

  // expect(checkAnswer(answer)).toBeOneOf([
  //   "very positive",
  //   "positive",
  //   "negative",
  //   "very negative",
  // ]);
});
`
