### ISSUE TITLE
Builds are failing on the run extra-tests check. 

### ISSUE THREAD

**Issue by jcholyhead** [CodeYourFuture/JavaScript-Core-1-Coursework-Week1#334]
Builds are failing on the run extra-steps Action. 

Possibly related to Open issue #224 

Example build output 

`Run npm run extra-tests
npm ERR! Missing script: "extra-tests"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-08-01T12_15_[4](https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/runs/7610994022?check_suite_focus=true#step:4:5)[5](https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/runs/7610994022?check_suite_focus=true#step:4:6)_42[8](https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/runs/7610994022?check_suite_focus=true#step:4:9)Z-debug-0.log
Error: Process completed with exit code 1.`

**Comment by illicitonion** [comment]
@gregdyke it looks like https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/commit/c68d84e2f9fb8f0b9ac655aef7830f3f8af8e908 removed the run script for `extra-tests`, but didn't modify the github action in https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/master/.github/workflows/extra-tests.yml

As far as I can tell from a small sampling, the "projects" approach didn't get rolled out to any other repos.

What's the desired end state here? 100% of repos using projects (and having their actions updated), or 100% of projects using separate run scripts (and this one repo having its actions reverted)? I don't have a particular dog in this race either way, but we should converge on one consistent approach :)
