### ISSUE TITLE
Tests need to be reviewed on mandatory folder - exercise 4-tax

### ISSUE THREAD

**Issue by Laura-TM** [CodeYourFuture/JavaScript-Core-1-Coursework-Week1#80]
On the first function, it asks you to calculate the tax (e.g. if you want to put a 20% sales tax on top of a coat priced at £80, the sales tax is £16), but the tests are expecting you to provide the full price: original price plus sales tax (e.g. 80 + 16 = 96). The second function then asks you to utilise the information from the calculate tax function to get the full price (original price plus tax to be added on top).

**Comment by ChrisOwen101** [comment]
Thanks Laura! I've tweaked the task description to fix this.
